source 'https://rubygems.org'

ruby '2.2.0'

gem 'rails', '~> 4.1.9'

gem 'pg', '~> 0.18.1'
gem 'sass-rails', '~> 5.0.1'
gem 'uglifier'

gem 'jquery-rails', '~> 3.1.2'
gem 'jquery-ui-rails', '~> 4.2.0'
gem 'angularjs-rails', '~> 1.3.9'

gem 'jbuilder', '~> 2.2.6'

group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', '~>0.4.1', require: false
end

group :test, :development do
  gem 'rspec-rails', '3.0'
  gem 'launchy'
  gem 'pry-byebug', '~> 2.0.0'
  gem 'capybara-rails', '~> 0.0.2'
  gem 'selenium-webdriver', '~> 2.44.0'
  gem 'database_cleaner', '~> 1.4.0'
  gem 'license_finder', '~> 0.9.5.1'
  gem 'jasmine', '~> 2.1.0'
  gem 'jasmine-jquery-rails', '~> 2.0.3'
  gem 'unicorn-rails', '2.2.0'
  gem 'rails-erd'
  gem 'spring', '~>1.2.0'
  gem 'spring-commands-rspec', '~>1.0.4'
  gem 'rspec-retry', '~> 0.3.0'
end





